
cut: 
	sed -i -e 's,+---------+---------------+----------+,,g' tb_pack
	sed -i -e '/ETHER/d' tb_pack
	sed -i -e 's,|,,g' tb_pack
	sed -i -e 's,0   ,,g' tb_pack
	sed -i -e '1d' tb_pack
	sed -i -e 'n;n;d' tb_pack
	sed -i -e 'n;d' tb_pack
